# Experiment details
EXPName: Total Factor Productivity
Region: Oklahoma
code: OK
Fields_of_Interest: ./CropRotationMaps/OKRotFilt.shp
# Area_of_Interest: 
# Grid_resoultion: #(in km)
Processed_Info:

# Model details
EPICModel: ./model/EPIC2301dt20230820
start_year: 1995
duration: 25
output_types:
  - ACY  # Annual Crop Yield
  - ACM
output_dir: ./output
log_dir: ./log

# Weather configuration
weather:
  dir: ./weather
  start_date: '1981-01' # year and month
  end_date: '2020-12'
  offline: false  # if true, the data is assumed to be already downloaded.

# Soil details
soil:
  gdb_path: ./soil/gSSURGO_OK.gdb
  files_dir:    #if not empty, processing gdb file is skipped

# Site details
sites:
  dir: ./sites
  slope_len: ./soil/OK_slopelen_1.csv
  elevation: /home/bharath20/SRTM_1km_US_project.tif
  slope_us: /home/bharath20/slope_us.tif
  ssurgo_map: /home/bharath20/SSURGO.tif

# OPC details
opc_dir: ./opc
opc_prefix: CropRot


# Run params
Range: [0, 0.25]
num_of_workers: 80
